name: Build

on:
    push:
        branches: ["**"]
        tags: ["**"]
        paths-ignore: ["**.md"]
    workflow_call:
    workflow_dispatch:
        inputs:
            publish:
                description: 'Publish to Packages as a snapshot'
                type: boolean
                required: false
                default: false

            release:
                description: 'Publish a release with this tag'
                type: string
                required: false
                default: ''

permissions:
    contents: read
    packages: read

jobs:
    build-natives:
        permissions:
            contents: read
        uses: ./.github/workflows/build-natives.yml

    build:
        needs: build-natives
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: Download natives
              uses: actions/download-artifact@v8
              with:
                  name: natives-resources
                  path: main/build/embedded-natives

            - name: Setup Java
              uses: actions/setup-java@v5
              with:
                  distribution: zulu
                  java-version: 17  # gradle 9 requires Java 17
                  cache: gradle

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v6
              with:
                  cache-provider: 'basic'

            - name: Build project
              run: ./gradlew build

            - name: Publish packages
              if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && inputs.publish == 'true') }}
              env:
                  GITHUB_PACKAGES_USERNAME: ${{ github.actor }}
                  GITHUB_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
              run: ./gradlew publish

            - name: Upload Artifacts
              uses: actions/upload-artifact@v7
              with:
                  name: lavaplayer-artifacts
                  path: |
                      main/build/libs/lavaplayer-*.jar
                      common/build/libs/lava-common-*.jar
                      extensions/format-xm/build/libs/lavaplayer-ext-format-xm-*.jar

    release:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: write
        if: ${{ (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) || (github.event_name == 'workflow_dispatch' && inputs.release != '') }}
        steps:
            - name: Get the tag name
              id: get_tag
              run: |
                    if [ "${{ github.event_name }}" = "push" ]; then
                        echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
                    elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
                        echo "TAG_NAME=${{ inputs.release }}" >> $GITHUB_ENV
                    else
                        echo "TAG_NAME=unknown" >> $GITHUB_ENV
                    fi

            - name: Download build artifacts
              uses: actions/download-artifact@v8
              with:
                  name: lavaplayer-artifacts
                  path: release-artifacts

            - name: Publish GitHub Release
              uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda
              with:
                  tag_name: ${{ env.TAG_NAME }}
                  files: "release-artifacts/**/*.jar"
